SELECT ED.ID
FROM ECOLI_DATA ED
JOIN (SELECT ED.ID
     FROM ECOLI_DATA ED
     JOIN (SELECT ID
          FROM ECOLI_DATA
          WHERE PARENT_ID is NULL) FG
     ON ED.PARENT_ID = FG.ID) SG
ON ED.PARENT_ID = SG.ID
ORDER BY ID asc