SELECT ID
, CASE WHEN CNT THEN CNT ELSE 0 END as CHILD_COUNT
FROM ECOLI_DATA EDP
LEFT JOIN (SELECT PARENT_ID,COUNT(PARENT_ID) as CNT
      FROM ECOLI_DATA
      GROUP BY PARENT_ID) EDC
ON EDP.ID = EDC.PARENT_ID
ORDER BY ID