SELECT ID
,CASE WHEN SOC = 1 THEN 'CRITICAL'
      WHEN SOC = 2 THEN 'HIGH'
      WHEN SOC = 3 THEN 'MEDIUM'
      ELSE 'LOW' END as COLONY_NAME
FROM (SELECT ID
      ,NTILE(4) over (ORDER BY SIZE_OF_COLONY DESC) as SOC
      FROM ECOLI_DATA) ED
ORDER BY ID