SELECT YEAR(ED.DIFFERENTIATION_DATE) as YEAR
, MAX_SIZE - SIZE_OF_COLONY as YEAR_DEV
, ID
FROM ECOLI_DATA ED
LEFT JOIN 
(SELECT YEAR(DIFFERENTIATION_DATE) as YEAR
 , MAX(SIZE_OF_COLONY) as MAX_SIZE 
 FROM ECOLI_DATA 
 GROUP BY YEAR) MS
ON YEAR(ED.DIFFERENTIATION_DATE) = MS.YEAR
ORDER BY YEAR asc, YEAR_DEV asc