SELECT FI.ID, FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN (SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) ML
ON FI.FISH_TYPE = ML.FISH_TYPE
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH = ML.LENGTH
ORDER BY ID asc