SELECT SCORE,HE.EMP_NO,EMP_NAME,POSITION,EMAIL
FROM HR_EMPLOYEES HE 
join (SELECT EMP_NO, sum(SCORE) as SCORE 
      FROM HR_GRADE 
      GROUP BY EMP_NO) HG
on HE.EMP_NO = HG.EMP_NO
ORDER BY SCORE desc
LIMIT 1