SELECT COUNT(*) as FISH_COUNT
, MAX(LENGTH) as MAX_LENGTH
, FI.FISH_TYPE
FROM FISH_INFO FI
JOIN (SELECT FISH_TYPE
      , AVG(LENGTH) as AVERAGE_LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) AL
ON FI.FISH_TYPE = AL.FISH_TYPE
WHERE AVERAGE_LENGTH >= 33
GROUP BY FISH_TYPE
ORDER BY FI.FISH_TYPE asc